version: '3.9'
services:
  client:
    image: nginx:latest
    volumes:
      - ./:/usr/share/nginx/html
    restart: always
    ports:
      - "8081:80"
    logging:
      options:
        max-size: "1m"
        max-file: "3"